export const CREATE_PARTICIPANT_MUTATION_KEY = "CREATE_EVENT_MUTATION_KEY";
export const UPDATE_PARTICIPANT_MUTATION_KEY = "UPDATE_PARTICIPANT_MUTATION_KEY";
export const DELETE_PARTICIPANT_MUTATION_KEY = "DELETE_PARTICIPANT_MUTATION_KEY";
export const PARTICIPANT_QUERY_KEY = "PARTICIPANT_QUERY_KEY";
