export const INSERT_USERS_MUTATION_KEY = "INSERT_USERS_MUTATION_KEY";
export const UPDATE_USERS_MUTATION_KEY = "UPDATE_USERS_MUTATION_KEY";
export const DELETE_USER_MUTATION = "DELETE_USER_MUTATION";
export const USERS_QUERY_KEY = "USERS_QUERY_KEY";
export const UPLOAD_PROFILE_IMAGE_MUTATION_KEY = "UPLOAD_PROFILE_IMAGE_MUTATION_KEY";
export const DELETE_PROFILE_IMAGE_MUTATION_KEY = "DELETE_PROFILE_IMAGE_MUTATION_KEY";
export const PROFILE_PICTURE_QUERY_KEY = "PROFILE_PICTURE_QUERY_KEY";
