export const INSERT_USERS_MUTATION_KEY = "INSERT_USERS_MUTATION_KEY";
export const UPDATE_USERS_MUTATION_KEY = "UPDATE_USERS_MUTATION_KEY";
export const DELETE_USER_MUTATION = "DELETE_USER_MUTATION";
export const USERS_QUERY_KEY = "USERS_QUERY_KEY";
