export const UPLOAD_PROFILE_IMAGE_MUTATION_KEY = 'UPLOAD_PROFILE_IMAGE_MUTATION_KEY';
export const DELETE_PROFILE_IMAGE_MUTATION_KEY = 'DELETE_PROFILE_IMAGE_MUTATION_KEY';
export const PROFILE_PICTURE_QUERY_KEY = 'PROFILE_PICTURE_QUERY_KEY';

export const UPLOAD_EVENT_IMAGE_MUTATION_KEY = 'UPLOAD_EVENT_PICTURE_MUTATION_KEY';
export const REMOVE_EVENT_IMAGE_MUTATION_KEY = 'REMOVE_EVENT_IMAGE_MUTATION_KEY';
export const DELETE_EVENT_IMAGE_MUTATION_KEY = 'DELETE_EVENT_IMAGE_MUTATION_KEY';
export const EVENT_IMAGE_QUERY_KEY = 'UPLOAD_EVENT_PICTURE_MUTATION_KEY';
