export const CREATE_EVENT_MUTATION_KEY = "CREATE_EVENT_MUTATION_KEY";
export const UPDATE_EVENT_MUTATION_KEY = "UPDATE_EVENT_MUTATION_KEY";
export const DELETE_EVENT_MUTATION_KEY = "UPDATE_EVENT_MUTATION_KEY";
export const EVENTS_QUERY_KEY = "EVENTS_QUERY_KEY";
