export const CREATE_EVENT_MUTATION_KEY = "CREATE_EVENT_MUTATION_KEY";
export const UPDATE_EVENT_MUTATION_KEY = "UPDATE_EVENT_MUTATION_KEY";
export const DELETE_EVENT_MUTATION_KEY = "UPDATE_EVENT_MUTATION_KEY";
export const EVENTS_QUERY_KEY = "EVENTS_QUERY_KEY";

export const UPLOAD_EVENT_IMAGE_MUTATION_KEY = "UPLOAD_EVENT_PICTURE_MUTATION_KEY";
export const REMOVE_EVENT_IMAGE_MUTATION_KEY = "REMOVE_EVENT_IMAGE_MUTATION_KEY";
export const DELETE_EVENT_IMAGE_MUTATION_KEY = "DELETE_EVENT_IMAGE_MUTATION_KEY";
export const EVENT_IMAGE_QUERY_KEY = "UPLOAD_EVENT_PICTURE_MUTATION_KEY";
